services:
  - type: web
    name: mgnrega-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATA_GOV_API_KEY
        value: your-data-gov-api-key-here
    disk:
      name: mgnrega-data
      mountPath: /opt/render/project/server/database
      sizeGB: 1
